CREATE DATABASE tech_task_wg;

CREATE TABLE IF NOT EXISTS product(
	id INT UNSIGNED AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(100),
	amount INT UNSIGNED DEFAULT 0 NOT NULL,
	price FLOAT NOT NULL,
	creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ip VARCHAR(40) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS component(
	id INT UNSIGNED AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(100),
	amount INT UNSIGNED DEFAULT 0 NOT NULL,
	price FLOAT NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS product_component(
	product_id INT UNSIGNED NOT NULL,
	component_id INT UNSIGNED NOT NULL	
);

ALTER TABLE product_component ADD CONSTRAINT product_component_product FOREIGN KEY (product_id) REFERENCES product(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE product_component ADD CONSTRAINT product_component_component FOREIGN KEY (component_id) REFERENCES component(id) ON UPDATE CASCADE ON DELETE CASCADE;